server.port=${PORT:5000}
spring.application.name=skillsphere-backend

# Custom database configuration mapping from environment variables
skillsphere.db.host=${DB_HOST:localhost}
skillsphere.db.port=${DB_PORT:3306}
skillsphere.db.name=${DB_NAME:skillsphere_db}
skillsphere.db.username=${DB_USER:root}
skillsphere.db.password=${DB_PASSWORD:}

# JWT secrets config
skillsphere.jwt.access-secret=${JWT_ACCESS_SECRET:skillsphere_local_access_secret_12893718923}
skillsphere.jwt.refresh-secret=${JWT_REFRESH_SECRET:skillsphere_local_refresh_secret_9812739812}

# Google Client ID
skillsphere.google.client-id=${GOOGLE_CLIENT_ID:187668431914-r6bca92vusq2seqmopgfa9o5vrub4bi3.apps.googleusercontent.com}

# Hibernate / JPA configurations
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
